version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ryanzola-dev
    container_name: ryanzola-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
